name: 🐞 Bug Report
description: Let us know about a bug and help us improve!
labels: ["bug", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        For questions, the best place to get answers is on our [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions), as they will get more visibility from experienced users than the issue tracker.
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
        
        ---
  - type: dropdown
    id: os
    attributes:
      label: Operating System (Polypheny-DB)
      description: "On which operating system is Polypheny-DB running? "
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
    validations:
      required: false
  - type: input
    id: polypheny-db-version
    attributes:
      label: Polypheny-DB Version
      description: "Please provide the full Polypheny-DB version of your project. Or if you are in a dev environment your commit"
      placeholder: "v0.7.1"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected Areas
      description: Which areas of the project are affected
      multiple: true
      options:
        - DB
        - UI
        - Control
        - Client
        - Website
        - JDBC
        - Python
        - Something else (please specify in the description!)
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: "Which browser did you use to connect to the system? Only apply if aplicable."
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
    validations:
      required: false
  - type: input
    id: client-os
    attributes:
      label: Client Operating System
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: false
  - type: markdown
    attributes:
      value:
        ---
