name: 🐞 Bug Report
description: Let us know about a bug and help us improve!
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        |
        For questions, the best place to get answers is on our [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions), as they will get more visibility from experienced users than the issue tracker.
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: system-os
    attributes:
      label: System Operating System
      description: "Which operating system do you use to run Polyphney-DB? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true  
  - type: input
    id: client-os
    attributes:
      label: Client Operating System
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "Which operating system do you use? "
      options:
        - label: Linux
        - label: Windows
        - label: macOS
    multiple: true
    validations:
      required: true
  - type: input
    id: polypheny-db-version
    attributes:
      label: Polypheny-DB Version
      description: "Please provide the full Polypheny-DB version of your project."
      placeholder: "v0.7.1"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected Areaa
      description: Which areas of the project are affected
      options:
        - DB
        - UI
        - Control
        - Client
        - Website
        - JDBC
        - Python
        - Something else (please specify in the description!)
    multiple: true
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
